---
exclude_paths:
  - "internal/**"
  - "**/*_test.go"
  - ".codacy.yml"
  - "commitlint.config.js"
  - "config.yml"
  - ".github/**"
  - "package-lock.json"
  - ".pre-commit-config.yaml"
  - ".vscode/**"
  