name: Codacy Analysis CLI and coverage report

on: ["push"]

jobs:
  codacy-analysis-cli:
    name: Codacy Analysis CLI
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@main

      - name: Run Codacy Analysis CLI
        uses: codacy/codacy-analysis-cli-action@master
  test-and-coverage:
    runs-on: ubuntu-latest
    name: test-and-coverage
    steps:
      - uses: actions/checkout@v2
      - name: Run test and coverage
        run: ./scripts/test.sh
      - name: Send coverage
        run: CODACY_PROJECT_TOKEN=${{ secrets.CODACY_PROJECT_TOKEN }} bash <(curl -Ls https://coverage.codacy.com/get.sh) report --force-coverage-parser go -r coverage.out
